apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic
    spec:
      containers:
        - name: springpetclinic
          image: louay1732001/petclinic:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

